Nickdowell/event uploader
bugsnag/bugsnag-cocoa pull request #1009
Opened 2021-02-22 15:18 UTC by nickdowell

## Goal

## Design

## Changeset

## Testing

2021-03-04 11:31 UTC, kstenerud requested changes

2021-03-04 13:15 UTC, nickdowell commented on Bugsnag/Delivery/BSGEventUploadFileOperation.m
> +    // TODO: Load a BugsnagEvent from json file on disk
Yes - upload of bugsnag-formatted events from disk is planned to be part of a future PR

2021-03-04 13:16 UTC, nickdowell commented on Bugsnag/Delivery/BSGEventUploadKSCrashReportOperation.m
> +    id json = [BSGJSONSerialization JSONObjectWithData:data options:0 error:errorPtr];
Correct; if the JSON is invalid then the report will not be sent. This is intended & same as the current behaviour.

2021-03-04 13:17 UTC, nickdowell commented on Bugsnag/Delivery/BSGEventUploadKSCrashReportOperation.m
> +    crashReport[@BSG_KSCrashField_Diagnosis] = [doctor diagnoseCrash:report];
Yes; it is used by [BSGParseErrorMessage()](https://github.com/bugsnag/bugsnag-cocoa/blob/nickdowell/event-uploader/Bugsnag/Payload/BugsnagError.m#L65-L73)

2021-03-04 13:19 UTC, nickdowell commented on Bugsnag/Delivery/BSGEventUploadObjectOperation.m
> +@implementation BSGEventUploadObjectOperation
The purpose of this class is to upload a `BugsnagEvent` that has not been persisted to disk.

The event gets persisted to disk if the upload fails, and its superclass contains the logic for uploading.

2021-03-04 13:45 UTC, nickdowell commented on Bugsnag/Delivery/BSGEventUploadOperation.m
> +- (void)storeEventPayload:(NSDictionary *)eventPayload inDirectory:(NSString *)directory {
I think this is probably worth discussing in person, it's a consequence of the design choice to use subclassing to represent the different kinds of uploads.

2021-03-04 15:57 UTC, kstenerud commented on Bugsnag/Delivery/BSGEventUploadOperation.m
> +- (void)storeEventPayload:(NSDictionary *)eventPayload inDirectory:(NSString *)directory {
After in-person discussion, I have no issues with this

2021-03-04 15:58 UTC, kstenerud approved these changes

2021-03-05 11:17 UTC, nickdowell commented
This PR was merged manually to resolve the conflicts

2021-03-05 11:17 UTC, closed without merging