Allow overriding the unhandled flag in non-fatal errors.
bugsnag/bugsnag-cocoa pull request #912
Opened 2020-11-26 13:48 UTC by kstenerud

## Goal

Make the `unhandled` property of `BugsnagEvent` writable, and trace if it has been changed.

## Design

See ROAD-732

## Changeset

TBD

## Testing

TBD

2020-11-27 09:35 UTC, nickdowell requested changes
The changes look good 👍 

I think there needs to be some coverage added for this in the E2E tests, though

2020-11-27 09:35 UTC, nickdowell commented on Tests/BugsnagErrorReportSinkTests.m
> +    XCTAssertEqualObjects(@"warning", payload[@"severity"]);
The arguments are the wrong way round; the expected value should be the second argument to `XCTAssertEqualObjects`

The same comment applies to the other uses of `XCTAssertEqualObjects` in this test method.

2020-12-01 15:32 UTC, nickdowell approved these changes

2020-12-01 16:46 UTC, kattrali commented on Bugsnag/Payload/BugsnagHandledState.m
> +    dict[kUnhandledOverridden] = @(self.unhandledOverridden);
This is specified in the product design to default to `false` if omitted, so a check here to avoid sending a few extra bytes seems reasonable.

2020-12-02 12:56 UTC, merged