[PLAT-5449] Include metadata in OOM events
bugsnag/bugsnag-cocoa pull request #915
Opened 2020-11-26 16:50 UTC by nickdowell

## Goal

OOM events were missing some important data that are present in other types of error:

* custom metadata provided by the app developer
* user information

The changes in this PR add this information to OOMs.

## Design

See the design document on Confluence.

## Changeset

Metadata is now written to files on disk and read from there when constructing a KSCrashReport.

`-[BugsnagEvent initWithOOMData:]` has been amended to use this newly available information.

The device data being captured in `BugsnagSystemState` becomes redundant as it exists in the "state" metadata, so has been removed.

`out_of_memory.feature` no longer checks for `device.orientation` because that is not present in other types of error.

## Testing

Manually verified by triggering OOMs and examining payload.

2020-11-27 15:21 UTC, kstenerud requested changes

2020-11-27 15:21 UTC, kstenerud commented on Bugsnag/Client/BugsnagClient.m
> +        [_configMetadataFile getFileSystemRepresentation:bsg_g_bugsnag_data.configPath maxLength:sizeof(bsg_g_bugsnag_data.configPath)];
We should check the return value for failure

2020-11-27 15:21 UTC, kstenerud commented on Bugsnag/Client/BugsnagClient.m
> +        [crashPath getFileSystemRepresentation:crashSentinelPath maxLength:sizeof(crashSentinelPath)];
We should check the return value for failure

2020-11-27 15:21 UTC, kstenerud commented on Bugsnag/Client/BugsnagClient.m
> +        [_metadataFile getFileSystemRepresentation:bsg_g_bugsnag_data.metadataPath maxLength:sizeof(bsg_g_bugsnag_data.metadataPath)];
We should check the return value for failure

2020-11-27 15:21 UTC, kstenerud commented on Bugsnag/Client/BugsnagClient.m
> +        [_stateMetadataFile getFileSystemRepresentation:bsg_g_bugsnag_data.statePath maxLength:sizeof(bsg_g_bugsnag_data.statePath)];
We should check the return value for failure

2020-11-27 15:21 UTC, kstenerud commented on Bugsnag/Helpers/BSGJSONSerialization.m
> ++ (BOOL)writeJSONObject:(id)JSONObject toFile:(NSString *)file options:(NSJSONWritingOptions)options error:(NSError **)errorPtr {
These will need tests I think

2020-11-27 16:00 UTC, nickdowell commented on Bugsnag/Helpers/BSGJSONSerialization.m
> ++ (BOOL)writeJSONObject:(id)JSONObject toFile:(NSString *)file options:(NSJSONWritingOptions)options error:(NSError **)errorPtr {
Unit test case added 👍

2020-12-01 11:09 UTC, kstenerud approved these changes

2020-12-01 11:32 UTC, kattrali approved these changes

2020-12-01 11:53 UTC, merged